<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \Illuminate\Support\Facades\Schema::disableForeignKeyConstraints();
        Menu::truncate();
        \Illuminate\Support\Facades\Schema::enableForeignKeyConstraints();

        $menus = [
            [
                'id' => 1,
                'nama' => 'Main Menu',
                'route' => null,
                'icon' => null,
                'permission' => null,
                'parent_id' => null,
                'group' => null,
            ],
            [
                'id' => 2,
                'nama' => 'Dashboard',
                'route' => 'dashboard',
                'icon' => 'home',
                'permission' => ['view-dashboard'],
                'parent_id' => 1,
                'group' => null,
            ],
            [
                'id' => 3,
                'nama' => 'Dashboard Kamar',
                'route' => 'dashboard.kamar',
                'icon' => 'bed',
                'permission' => ['view-dashboard-kamar'],
                'parent_id' => 1,
                'group' => null,
            ],
            [
                'id' => 4,
                'nama' => 'User',
                'route' => 'admin.user.index',
                'icon' => 'users',
                'permission' => ['tanda-tangan-digital', 'view-admin-user'],
                'parent_id' => 1,
                'group' => 'admin',
            ],
            [
                'id' => 5,
                'nama' => 'Settings',
                'route' => null,
                'icon' => 'settings',
                'permission' => [],
                'parent_id' => 1,
                'group' => 'admin',
            ],
            [
                'id' => 6,
                'nama' => 'Menu',
                'route' => 'admin.settings.menu',
                'icon' => null,
                'permission' => ['view-admin-settings-menu'],
                'parent_id' => 5,
                'group' => 'admin',
            ],
            [
                'id' => 7,
                'nama' => 'Perusahaan',
                'route' => 'admin.settings.perusahaan',
                'icon' => null,
                'permission' => ['view-admin-settings-perusahaan'],
                'parent_id' => 5,
                'group' => 'admin',
            ],
            [
                'id' => 8,
                'nama' => 'Role Permission',
                'route' => null,
                'icon' => 'circle-key',
                'permission' => [],
                'parent_id' => 1,
                'group' => 'admin',
            ],
            [
                'id' => 9,
                'nama' => 'Role',
                'route' => 'admin.settings.role',
                'icon' => null,
                'permission' => ['view-admin-settings-role'],
                'parent_id' => 8,
                'group' => 'admin',
            ],
            [
                'id' => 10,
                'nama' => 'Permission',
                'route' => 'admin.settings.permission',
                'icon' => null,
                'permission' => ['view-admin-settings-permission'],
                'parent_id' => 8,
                'group' => 'admin',
            ],
            [
                'id' => 11,
                'nama' => 'Karyawan',
                'route' => 'kepegawaian.karyawan.index',
                'icon' => 'user-square',
                'permission' => ['edit-kepegawaian-karyawan', 'export-karyawan', 'view-dokter', 'view-kepegawaian-karyawan'],
                'parent_id' => 1,
                'group' => 'sdm',
            ],
            [
                'id' => 12,
                'nama' => 'Master',
                'route' => null,
                'icon' => 'database',
                'permission' => [],
                'parent_id' => 1,
                'group' => 'sdm',
            ],
            [
                'id' => 13,
                'nama' => 'Bagian',
                'route' => 'kepegawaian.master.bagian.index',
                'icon' => null,
                'permission' => ['view-kepegawaian-master-bagian'],
                'parent_id' => 12,
                'group' => 'sdm',
            ],
            [
                'id' => 14,
                'nama' => 'Jabatan',
                'route' => 'kepegawaian.master.jabatan.index',
                'icon' => null,
                'permission' => ['view-kepegawaian-master-jabatan'],
                'parent_id' => 12,
                'group' => 'sdm',
            ],
            [
                'id' => 15,
                'nama' => 'Ruangan',
                'route' => 'kepegawaian.master.ruangan.index',
                'icon' => null,
                'permission' => ['view-kepegawaian-master-ruangan'],
                'parent_id' => 12,
                'group' => 'sdm',
            ],
            [
                'id' => 16,
                'nama' => 'Spesialis',
                'route' => 'kepegawaian.master.spesialisasi.index',
                'icon' => null,
                'permission' => ['view-kepegawaian-master-spesialisasi'],
                'parent_id' => 12,
                'group' => 'sdm',
            ],
            [
                'id' => 17,
                'nama' => 'Surat',
                'route' => null,
                'icon' => 'mail-opened',
                'permission' => [],
                'parent_id' => 1,
                'group' => 'sdm',
            ],
            [
                'id' => 19,
                'nama' => 'SP3',
                'route' => 'kepegawaian.surat.sp3',
                'icon' => null,
                'permission' => ['view-kepegawaian-surat-sp3'],
                'parent_id' => 17,
                'group' => 'sdm',
            ],
            [
                'id' => 20,
                'nama' => 'Master',
                'route' => null,
                'icon' => 'database',
                'permission' => [],
                'parent_id' => 1,
                'group' => 'umu',
            ],
            [
                'id' => 21,
                'nama' => 'Supplier',
                'route' => 'umum.master.supplier',
                'icon' => null,
                'permission' => ['view-umum-master-supplier'],
                'parent_id' => 20,
                'group' => 'umu',
            ],
            [
                'id' => 22,
                'nama' => 'Jasmed',
                'route' => 'kepegawaian.jasmed.index',
                'icon' => 'chart-pie',
                'permission' => ['jasmed-bpjs', 'jasmed-jkmd', 'view-kepegawaian-jasmed'],
                'parent_id' => 1,
                'group' => 'sdm',
            ],
            [
                'id' => 23,
                'nama' => 'Kategori Barang',
                'route' => 'umum.master.kategori',
                'icon' => null,
                'permission' => ['view-umum-master-kategori'],
                'parent_id' => 20,
                'group' => 'umu',
            ],
            [
                'id' => 24,
                'nama' => 'Satuan Barang',
                'route' => 'umum.master.satuan',
                'icon' => null,
                'permission' => ['view-umum-master-satuan'],
                'parent_id' => 20,
                'group' => 'umu',
            ],
            [
                'id' => 25,
                'nama' => 'Penyimpanan',
                'route' => 'umum.master.penyimpanan',
                'icon' => null,
                'permission' => ['view-umum-master-penyimpanan'],
                'parent_id' => 20,
                'group' => 'umu',
            ],
            [
                'id' => 26,
                'nama' => 'Barang',
                'route' => 'umum.master.barang',
                'icon' => null,
                'permission' => ['view-umum-master-barang'],
                'parent_id' => 20,
                'group' => 'umu',
            ],
            [
                'id' => 27,
                'nama' => 'Pembelian',
                'route' => 'umum.pembelian.index',
                'icon' => 'shopping-cart-plus',
                'permission' => ['view-umum-pembelian'],
                'parent_id' => 1,
                'group' => 'umu',
            ],
            [
                'id' => 28,
                'nama' => 'Distribusi',
                'route' => 'umum.distribusi.index',
                'icon' => 'shopping-cart-share',
                'permission' => ['view-umum-distribusi'],
                'parent_id' => 1,
                'group' => 'umu',
            ],
            [
                'id' => 29,
                'nama' => 'Gudang',
                'route' => 'umum.gudang.index',
                'icon' => 'package',
                'permission' => ['view-umum-gudang'],
                'parent_id' => 1,
                'group' => 'umu',
            ],
            [
                'id' => 30,
                'nama' => 'Asset',
                'route' => 'umum.asset.index',
                'icon' => 'device-ipad-horizontal-check',
                'permission' => ['view-umum-asset'],
                'parent_id' => 1,
                'group' => 'umu',
            ],
            [
                'id' => 31,
                'nama' => 'Hutang',
                'route' => 'keuangan.hutang.index',
                'icon' => 'file-invoice',
                'permission' => ['view-keuangan-hutang'],
                'parent_id' => 1,
                'group' => 'keu',
            ],
            [
                'id' => 32,
                'nama' => 'Piutang',
                'route' => 'keuangan.piutang.index',
                'icon' => 'file-dollar',
                'permission' => ['view-keuangan-piutang'],
                'parent_id' => 1,
                'group' => 'keu',
            ],
            [
                'id' => 33,
                'nama' => 'Laporan',
                'route' => 'umum.laporan.index',
                'icon' => 'file-analytics',
                'permission' => ['view-umum-laporan'],
                'parent_id' => 1,
                'group' => 'umu',
            ],
            [
                'id' => 34,
                'nama' => 'Stok Opname',
                'route' => 'umum.opname.index',
                'icon' => 'align-box-left-stretch',
                'permission' => ['finish-opname-gudang', 'view-umum-opname'],
                'parent_id' => 1,
                'group' => 'umu',
            ],
            [
                'id' => 35,
                'nama' => 'Laporan',
                'route' => 'keuangan.laporan.index',
                'icon' => 'file-analytics',
                'permission' => ['view-keuangan-laporan'],
                'parent_id' => 1,
                'group' => 'keu',
            ],
            [
                'id' => 36,
                'nama' => 'Verifikasi',
                'route' => 'surat.verification',
                'icon' => '',
                'permission' => ['view-surat-verification'],
                'parent_id' => 17,
                'group' => 'sdm',
            ],
            [
                'id' => 37,
                'nama' => 'Maintenance',
                'route' => 'umum.maintenance.index',
                'icon' => 'device-desktop-cog',
                'permission' => ['approval-maintenance', 'view-umum-maintenance'],
                'parent_id' => 1,
                'group' => 'umu',
            ],
            [
                'id' => 38,
                'nama' => 'Pengajuan',
                'route' => 'umum.pengajuan.index',
                'icon' => 'send',
                'permission' => ['view-umum-pengajuan'],
                'parent_id' => 1,
                'group' => 'umu',
            ],
            [
                'id' => 39,
                'nama' => 'Laporan',
                'route' => 'kepegawaian.laporan.index',
                'icon' => 'file-analytics',
                'permission' => ['view-kepegawaian-laporan'],
                'parent_id' => 1,
                'group' => 'sdm',
            ],
            [
                'id' => 40,
                'nama' => 'Akreditasi',
                'route' => null,
                'icon' => 'brand-google-drive',
                'permission' => ['assesor-akreditasi', 'view-kepegawaian-akreditasi'],
                'parent_id' => 1,
                'group' => 'sdm',
            ],
            [
                'id' => 64,
                'nama' => 'Semua Kegiatan',
                'route' => 'kepegawaian.akreditasi.index',
                'icon' => null,
                'permission' => ['view-kepegawaian-akreditasi'],
                'parent_id' => 40,
                'group' => 'sdm',
            ],
            [
                'id' => 42,
                'nama' => 'Pengaturan Cuti',
                'route' => 'kepegawaian.master.cuti.index',
                'icon' => null,
                'permission' => ['view-kepegawaian-master-cuti'],
                'parent_id' => 12,
                'group' => 'sdm',
            ],
            [
                'id' => 43,
                'nama' => 'Izin dan Cuti',
                'route' => 'kepegawaian.surat.cuti',
                'icon' => null,
                'permission' => ['create-cuti-other-karyawan', 'view-kepegawaian-surat-cuti'],
                'parent_id' => 17,
                'group' => 'sdm',
            ],
            [
                'id' => 45,
                'nama' => 'Akuntansi',
                'route' => null,
                'icon' => 'align-box-center-stretch',
                'permission' => [],
                'parent_id' => 1,
                'group' => 'keu',
            ],
            [
                'id' => 46,
                'nama' => 'COA',
                'route' => 'keuangan.akuntansi.coa',
                'icon' => null,
                'permission' => ['view-keuangan-akuntansi-coa'],
                'parent_id' => 45,
                'group' => 'keu',
            ],
            [
                'id' => 47,
                'nama' => 'Jurnal',
                'route' => 'keuangan.akuntansi.jurnal.umum',
                'icon' => null,
                'permission' => ['view-keuangan-akuntansi-jurnal-umum'],
                'parent_id' => 45,
                'group' => 'keu',
            ],
            [
                'id' => 48,
                'nama' => 'Golongan',
                'route' => null,
                'icon' => null,
                'permission' => [],
                'parent_id' => 12,
                'group' => 'sdm',
            ],
            [
                'id' => 49,
                'nama' => 'Master',
                'route' => null,
                'icon' => 'database',
                'permission' => [],
                'parent_id' => 1,
                'group' => 'keu',
            ],
            [
                'id' => 50,
                'nama' => 'Rekanan',
                'route' => 'keuangan.master.rekanan',
                'icon' => null,
                'permission' => ['view-keuangan-master-rekanan', 'add-keuangan-master-rekanan', 'edit-keuangan-master-rekanan', 'delete-keuangan-master-rekanan'],
                'parent_id' => 49,
                'group' => 'keu',
            ],
            [
                'id' => 52,
                'nama' => 'Pasien',
                'route' => 'administrasi.pasien.index',
                'icon' => 'users',
                'permission' => ['view-administrasi-pasien-index', 'add-administrasi-pasien-index', 'edit-administrasi-pasien-index', 'delete-administrasi-pasien-index'],
                'parent_id' => 1,
                'group' => 'admin',
            ],
            [
                'id' => 53,
                'nama' => 'Penggajian',
                'route' => 'kepegawaian.gaji.index',
                'icon' => 'moneybag',
                'permission' => ['view-kepegawaian-gaji-index', 'add-kepegawaian-gaji-index', 'edit-kepegawaian-gaji-index', 'delete-kepegawaian-gaji-index'],
                'parent_id' => 1,
                'group' => 'sdm',
            ],
            [
                'id' => 54,
                'nama' => 'Pendaftaran',
                'route' => 'administrasi.registrasi.index',
                'icon' => 'notes',
                'permission' => ['view-administrasi-registrasi-index', 'add-administrasi-registrasi-index', 'edit-administrasi-registrasi-index', 'delete-administrasi-registrasi-index'],
                'parent_id' => 1,
                'group' => 'admin',
            ],

            // ── Jadwal & Kehadiran (Fase 0 & 1) ──
            [
                'id' => 57,
                'nama' => 'Jadwal & Kehadiran',
                'route' => null,
                'icon' => 'calendar-time',
                'permission' => ['view-kepegawaian-jadwal-kerja'],
                'parent_id' => 1,
                'group' => 'sdm',
            ],
            [
                'id' => 55,
                'nama' => 'Jadwal Kerja',
                'route' => 'kepegawaian.jadwal-kerja.index',
                'icon' => null,
                'permission' => ['view-kepegawaian-jadwal-kerja'],
                'parent_id' => 57,
                'group' => 'sdm',
            ],
            [
                'id' => 56,
                'nama' => 'Jadwal Kerja Saya',
                'route' => 'profile.jadwal-tugas-saya',
                'icon' => null,
                'permission' => ['view-profile-jadwal-tugas-saya'],
                'parent_id' => 57,
                'group' => 'sdm',
            ],
            [
                'id' => 64,
                'nama' => 'Kontrol Absensi',
                'route' => 'kepegawaian.absensi.index',
                'icon' => null,
                'permission' => ['view-kepegawaian-absensi'],
                'parent_id' => 57,
                'group' => 'sdm',
            ],
            [
                'id' => 66,
                'nama' => 'Konfigurasi Jadwal',
                'route' => 'kepegawaian.konfigurasi-jadwal.index',
                'icon' => null,
                'permission' => ['view-kepegawaian-konfigurasi-jadwal'],
                'parent_id' => 57,
                'group' => 'sdm',
            ],
        ];

        foreach ($menus as $menuData) {
            $group = $menuData['group'];
            if ($group === 'adm') {
                $group = 'admin';
            }

            if (!empty($menuData['permission'])) {
                foreach ($menuData['permission'] as $permName) {
                    Permission::firstOrCreate(['name' => $permName]);
                }
            }

            Menu::create([
                'id'           => $menuData['id'],
                'nama'         => $menuData['nama'],
                'route'        => $menuData['route'],
                'route_params' => $menuData['route_params'] ?? null,
                'icon'         => $menuData['icon'],
                'permission'   => !empty($menuData['permission']) ? $menuData['permission'] : null,
                'group'        => $group,
                'parent_id'    => $menuData['parent_id'],
            ]);
        }
    }
}
