<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'view-dashboard',
            'view-dashboard-kamar',
            'view-user',
            'view-settings',
            'view-menus',
            'view-perusahaan',
            'view-role-permission',
            'view-roles',
            'view-permissions',
            'add-menu',
            'view-karyawan',
            'view-master',
            'view-bagian',
            'view-jabatan',
            'view-ruangan',
            'view-spesialis',
            'create-cuti-other-karyawan',
            'view-surat',
            'view-cuti',
            'view-sp3',
            'view-supplier',
            'view-jasmed',
            'view-kategori-barang',
            'view-satuan-barang',
            'view-penyimpanan',
            'view-barang',
            'view-pembelian',
            'view-distribusi',
            'view-gudang',
            'view-asset',
            'view-hutang',
            'view-piutang',
            'view-laporang',
            'view-stok-opname',
            'view-laporan',
            'export-karyawan',
            'view-dokter',
            'edit-karyawan',
            'tanda-tangan-digital',
            'view-verifikasi',
            'view-maintenance',
            'approval-maintenance',
            'jasmed-bpjs',
            'jasmed-jkmd',
            'view-pengajuan',
            'finish-opname-gudang',
            'view-akreditasi',
            'assesor-akreditasi',
            'view-pengaturan-cuti',
            'view-kepegawaian-master-cuti-index',
            'add-kepegawaian-master-cuti-index',
            'edit-kepegawaian-master-cuti-index',
            'delete-kepegawaian-master-cuti-index',
            'view-kepegawaian-surat-cuti',
            'add-kepegawaian-surat-cuti',
            'edit-kepegawaian-surat-cuti',
            'delete-kepegawaian-surat-cuti',
            'view-admin-user-index',
            'view-admin-settings-menu',
            'view-admin-settings-perusahaan',
            'view-admin-settings-role',
            'view-admin-user',
            'view-admin-settings-permission',
            'view-kepegawaian-karyawan',
            'edit-kepegawaian-karyawan',
            'view-kepegawaian-master-bagian',
            'view-kepegawaian-master-jabatan',
            'view-kepegawaian-master-ruangan',
            'view-kepegawaian-master-spesialisasi',
            'view-kepegawaian-surat-sp3',
            'view-umum-master-supplier',
            'view-kepegawaian-jasmed',
            'view-umum-master-kategori',
            'view-umum-master-satuan',
            'view-umum-master-penyimpanan',
            'view-umum-master-barang',
            'view-umum-pembelian',
            'view-umum-distribusi',
            'view-umum-gudang',
            'view-umum-asset',
            'view-keuangan-hutang',
            'view-keuangan-piutang',
            'view-umum-laporan',
            'view-umum-opname',
            'view-keuangan-laporan',
            'view-surat-verification',
            'view-umum-maintenance',
            'view-umum-pengajuan',
            'view-kepegawaian-laporan',
            'view-kepegawaian-akreditasi',
            'view-kepegawaian-master-cuti',
            'view-keuangan-akuntansi-coa',
            'view-keuangan-akuntansi-jurnal-umum',
            'view-keuangan-master-rekanan',
            'add-keuangan-master-rekanan',
            'edit-keuangan-master-rekanan',
            'delete-keuangan-master-rekanan',
            'view-administrasi-pasien-index',
            'add-administrasi-pasien-index',
            'edit-administrasi-pasien-index',
            'delete-administrasi-pasien-index',
            'view-administrasi-registrasi-index',
            'add-administrasi-registrasi-index',
            'edit-administrasi-registrasi-index',
            'delete-administrasi-registrasi-index',

            // ── Modul Penggajian (Payroll) ──
            'view-kepegawaian-gaji',
            'view-kepegawaian-gaji-index',
            'add-kepegawaian-gaji-index',
            'edit-kepegawaian-gaji-index',
            'delete-kepegawaian-gaji-index',
            'view-kepegawaian-gaji-rekap',
            'view-kepegawaian-gaji-detail',
            'approve-kepegawaian-gaji',
            'approve-kepegawaian-gaji-pajak',

            // ── Modul Penggajian: Master Aturan Pajak PPh 21 ──
            'view-kepegawaian-master-aturan-pajak',
            'add-kepegawaian-master-aturan-pajak',
            'edit-kepegawaian-master-aturan-pajak',
            'delete-kepegawaian-master-aturan-pajak',

            // ── Modul Penggajian: Master Tunjangan (Golongan, Jabatan, Lain-lain) ──
            'view-kepegawaian-master-tunjangan-golongan',
            'add-kepegawaian-master-tunjangan-golongan',
            'edit-kepegawaian-master-tunjangan-golongan',
            'delete-kepegawaian-master-tunjangan-golongan',
            'view-kepegawaian-master-tunjangan-jabatan',
            'add-kepegawaian-master-tunjangan-jabatan',
            'edit-kepegawaian-master-tunjangan-jabatan',
            'delete-kepegawaian-master-tunjangan-jabatan',
            'view-kepegawaian-master-tunjangan-lain',
            'add-kepegawaian-master-tunjangan-lain',
            'edit-kepegawaian-master-tunjangan-lain',
            'delete-kepegawaian-master-tunjangan-lain',

            // ── Modul Jadwal Kerja (Fase 0 & 1) ──
            'view-kepegawaian-jadwal-kerja',
            'add-kepegawaian-jadwal-kerja',
            'edit-kepegawaian-jadwal-kerja',
            'delete-kepegawaian-jadwal-kerja',
            'approve-jadwal-kabid',
            'approve-jadwal-wadir',
            'view-kepegawaian-absensi',
            'view-kepegawaian-konfigurasi-jadwal',
            'view-profile-jadwal-tugas-saya',
            'view-kepegawaian-master-jadwal-shift',
            'add-kepegawaian-master-jadwal-shift',
            'edit-kepegawaian-master-jadwal-shift',
            'delete-kepegawaian-master-jadwal-shift',
            'view-kepegawaian-master-jadwal-aturan',
            'add-kepegawaian-master-jadwal-aturan',
            'edit-kepegawaian-master-jadwal-aturan',
            'view-kepegawaian-master-ruangan-shift',
            'add-kepegawaian-master-ruangan-shift',
            'edit-kepegawaian-master-ruangan-shift',
            'delete-kepegawaian-master-ruangan-shift',
            'view-kepegawaian-master-bagian-koordinator',
            'add-kepegawaian-master-bagian-koordinator',
            'edit-kepegawaian-master-bagian-koordinator',
            'delete-kepegawaian-master-bagian-koordinator',
            'view-dashboard-poli',
            'edit-tgl-masuk-karyawan',
            // ── Hak Akses Eksekutif & Otorisasi Global ──
            'super-admin-bypass',
            'approve-kepegawaian-cuti',
            'approve-kepegawaian-sp3',
            'manage-umum-asset',
            'approve-umum-pengajuan',
            'manage-kepegawaian-master-aturan',
            'unlock-payroll-approved',
            'view-umum-maintenance-ticket-detail',
            'view-server-room-monitoring',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission]);
        }
    }
}
