  Dimas[m
  master[m
* [32mumum[m
  [31mremotes/origin/Dimas[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/HR[m
  [31mremotes/origin/fix/migrations[m
  [31mremotes/origin/master[m
  [31mremotes/origin/surya/prot[m
  [31mremotes/origin/umum[m
  [31mremotes/origin/upgrade/jasmed[m
  [31mremotes/origin/upgrade/livewire4-filament5[m
  [31mremotes/origin/upgrade/tailwind4-filament4-tallstackui3[m
